# ANIMAL_INS : 보호소에 들어온 동물
# ANIMAL_OUTS : 보호소에서 입양 보낸 동물의 정보
SELECT AI.ANIMAL_ID, AI.NAME
FROM ANIMAL_INS AS AI
INNER JOIN ANIMAL_OUTS AS AO
ON AI.ANIMAL_ID = AO.ANIMAL_ID
ORDER BY AO.DATETIME - AI.DATETIME DESC
LIMIT 2;