# 부서별 평균 연봉
SELECT HRE.DEPT_ID, HRD.DEPT_NAME_EN, ROUND(AVG(HRE.SAL)) AS AVG_SAL
FROM HR_EMPLOYEES AS HRE
INNER JOIN HR_DEPARTMENT AS HRD
ON HRE.DEPT_ID = HRD.DEPT_ID
GROUP BY DEPT_ID
ORDER BY AVG_SAL DESC;